stages:
  - test
  - build

test:
  stage: test
  image: golang:1.16
  script:
   - go test .

sonarqube-check:
 stage: test
 image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
 variables:
 script:
  - sonar-scanner -Dsonar.projectKey=My-Gitlab-project -Dsonar.sources=. -Dsonar.host.url=http://51.250.123.85:9000 -Dsonar.login=sqp_4e54f43e71f60669eff768c065dece72a7f90e5c

build:
  stage: build
  image: docker:latest
  only:
    - master
  script:
   - docker build .

build:
  stage: build
  image: docker:latest
  when: manual
  except:
    - master
  script:
   - docker build .


