stages:
  - test
  - build

test:
  stage: test
  image: golang:1.16
  script:
   - go test .

sonarqube-check:
 stage: test
 image:
  name: sonarsource/sonar-scanner-cli
  entrypoint: [""]
 variables:
 script:
  - sonar-scanner -Dsonar.projectKey=hw-8-03 -Dsonar.sources=. -Dsonar.host.url=http://158.160.1.110:9000 -Dsonar.login=sqa_216eb3720e5f8180481b6253865ada72f153abe1

build:
  stage: build
  image: docker:latest
  only:
    - master
  script:
   - docker build .

build:
  stage: build
  image: docker:latest
  when: manual
  except:
    - master
  script:
   - docker build .
